### ISSUE TITLE
Review: Activities.js and EditNonprofit.jsx

### ISSUE THREAD

**Issue by silviadebenedictis** [team-four-ics414/voluntree#44]
## Overview

The focus for this code review will be centered around the Activities.js and EditNonprofit.jsx pages.    
Please pay attention too:
* Javascript issues
* React components

## Review Branch

review-01

## Files to review

* Activities.js
* EditNonprofit.jsx

## Checklists

* [Architecture](../../checklists/architecture-checklist.md)
* [Design](../../checklists/design-checklist.md)
* [JS](../../checklists/js-checklist.md)
* [React](../../checklists/react-checklist.md)
* [Testing](../../checklists/testing-checklist.md)

## Due date

Monday, January 29th

## For more information

The review process is documented at: http://courses.ics.hawaii.edu/ics414s21/morea/review/reading-idpm-review.html

**Comment by silviadebenedictis** [comment]
### Activities.js

JS-08: Consider adding JSDoc comments to describe the purpose of the class constructor and methods.

### EditNonprofit.jsx

ESLINT-01: L3 'NumField' is defined but never used.

**Comment by joelvanta** [comment]
### Activities.js

JS-01: ‘benefits: String’ , ‘requirement, String’ what are these for?

### EditNonprofit.jsx

JS-01: ‘type’ what would it do?

**Comment by ThanhLy1** [comment]
# Code Review for `Activities.js` Class

## Utilizing `BaseCollection`

- **Issue**: The `ActivitiesCollection` class does not extend `BaseCollection`, leading to potential code duplication and missing out on the `BaseCollection`'s functionality.
- **Recommendation**: Extend `BaseCollection` to leverage its methods and structure.

## Schema Definition

- **Current Practice**: Defining a schema within `ActivitiesCollection`.
- **Improvement**: If `BaseCollection` handles schema attachment, utilize that feature instead of separate definition.

## Method Definition

- **Concern**: Redundant error handling in `Activities.insert` method.
- **Suggestion**: Ensure error handling isn't duplicated if `BaseCollection` already includes similar checks.
- **Note**: Consider using `ValidatedMethod` pattern for method definitions, similar to `BaseCollection`, instead of global `Meteor.methods`.

## Naming Conventions

- **Positive**: Appropriate naming of class and methods.
- **Advice**: Ensure consistent use of these names across the project.

## Code Readability

- **Observation**: Current code is readable.
- **Enhancement**: Inheritance from `BaseCollection` could improve readability by reducing redundancy.

# Suggestions for Improvement

- **Refactoring**: Refactor `ActivitiesCollection` to extend `BaseCollection`.
- **Adherence to DRY Principle**: Avoid repeating common logic by using inheritance.
- **Method Customization**: Override methods in `ActivitiesCollection` if customization is needed.
- **Testing and Documentation**: Ensure unit tests for `ActivitiesCollection` and use JSDoc comments for documentation.

# Conclusion

Refactoring `ActivitiesCollection` to extend `BaseCollection` will enhance maintainability, reduce redundancy, and ensure consistent operations across collections.

**Comment by zhuochenggan** [comment]
**Activities.js**
METEOR-03: Wrap Activities collection in a class with with define, update, and removeIt methods etc. 

**EditNonprofit.jsx**
ESLINT-01: L3 'NumField' is defined but never used.(no-unused-vars).

**Comment by mnakagawa14** [comment]
## Activities.js
### JS-01 Field names and datatypes
frequency: Should it be a binary repeating vs non-repeating?

requirement: Is this a text description of requirements? If so how is it different than details? Maybe could be a list of terms.

## EditNonprofit.jsx
### ESLINT-01 NumField isn't used
Should not be imported.

**Comment by mikhail-shkaralevich** [comment]
## Activities.js
The Activities collection should be implemented according to the pattern of the template we are using. Make Activities extend Base Collection.

## EditNonprofit.jsx
Fix eslint errors and add meaningful comments to the code.
